### ISSUE TITLE
Milestone 5 Feedback

### ISSUE THREAD

**Issue by matthewconnell** [kristinawright/group_09-1#16]
(I left this comment on Canvas as well because Github wasn't working an hour ago)

The dashboard looks great! There are just a couple small things I'll let you know about:

Bugs:
- [x] If you drop the 'price range' slider to zero, it causes an error.
- [x] If you de-select all the check boxes in either the district section or the house type section, it causes an error.

Layout:
- [x] Try to move the Linear/Log radio buttons down so that they're next to the violin plot
- [x] The title for the map is touching the header; it would be a good idea to move it down a bit.

Optional, less important stuff:
- [x] The violin plots could use a little color. The plain white theme of the plots stands out against the colorful map and sidebar.
- [x] I would move the data description to the bottom of the page.

Overall, great work! Let me know if you have problems implementing any of the changes.

**Comment by kristinawright** [comment]
All feedback was applied !

Kristina
